definitions:
  models.Computer:
    properties:
      computer_name:
        type: string
      description:
        type: string
      employee_abbreviation:
        type: string
      id:
        type: integer
      ip_address:
        type: string
      mac_address:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/computers:
    get:
      consumes:
      - application/json
      description: Retrieves all computer entries
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Computer'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all computers
      tags:
      - computers
    post:
      consumes:
      - application/json
      description: Creates a computer entry
      parameters:
      - description: Computer
        in: body
        name: computer
        required: true
        schema:
          $ref: '#/definitions/models.Computer'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Computer'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new computer
      tags:
      - computers
  /api/computers/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes a computer entry by its ID
      parameters:
      - description: Computer ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a computer by ID
      tags:
      - computers
    get:
      consumes:
      - application/json
      description: Retrieves a computer entry by its ID
      parameters:
      - description: Computer ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Computer'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a computer by ID
      tags:
      - computers
    put:
      consumes:
      - application/json
      description: Updates a computer entry by its ID
      parameters:
      - description: Computer ID
        in: path
        name: id
        required: true
        type: integer
      - description: Computer
        in: body
        name: computer
        required: true
        schema:
          $ref: '#/definitions/models.Computer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Computer'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a computer by ID
      tags:
      - computers
  /api/computers/{id}/assign/{abbr}:
    post:
      consumes:
      - application/json
      description: Assigns a computer to an employee by their abbreviation
      parameters:
      - description: Computer ID
        in: path
        name: id
        required: true
        type: integer
      - description: Employee Abbreviation
        in: path
        name: abbr
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Computer'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Assign a computer to an employee
      tags:
      - computers
  /api/computers/{id}/unassign:
    post:
      consumes:
      - application/json
      description: Unassigns a computer from an employee by its ID
      parameters:
      - description: Computer ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Computer'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Unassign a computer from an employee
      tags:
      - computers
  /api/employees/{abbr}/computers:
    get:
      consumes:
      - application/json
      description: Retrieves all computers assigned to an employee by their abbreviation
      parameters:
      - description: Employee Abbreviation
        in: path
        name: abbr
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Computer'
            type: array
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all computers assigned to an employee
      tags:
      - computers
swagger: "2.0"
